name: Go

on:
  push:
    branches: [ v2dev ]
  pull_request:
    branches: [ v2dev ]

jobs:
  test-build:
    name: Test & Build
    strategy:
      matrix:
        go-version: [ '1.19.x' ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: checkout
      uses: actions/checkout@v4

    - name: test
      run: |
        go mod tidy -v
        go test -race ./...
